### PR TITLE
Fixes and CI

### PR DESCRIPTION
**Pull request by michel2323**
* Remove Manifest.toml
* Remove deprecated warnings (CUDA shared memory)
* Fix type issue in eval functions
* Add CI

### CODE REVIEW

**Comment by michel2323** [comment]
@kibaekkim @youngdae Some small subset of tests fail. Do you want to fix them in this PR or should I mark them as `@test_broken` for now?

**Comment by michel2323** [comment]
Lol, ok, in the CI they pass. I don't get it. I have these errors locally:

**Comment by kibaekkim** [comment]
@michel2323 I have those errors locally.

**Comment by michel2323** [comment]
@kibaekkim It was that `try/catch` in `runtests.jl` that made them not appear here. Now they show here too.

**Review by kibaekkim — APPROVED** [review]
Looks good to me!

**Pull request merged**
